Question 35: Repeated Category Purchase
Difficulty: Easy
Link: https://www.interviewquery.com/questions/purchased-product?playlist=14-days-of-pandas

Problem Description:
===================
You’re analyzing a user’s purchases for a retail business.  
  
Each product belongs to a category. Your task is to identify which purchases represent the first
time the user has bought a product from its own category and which purchases represent repeat
purchases within the product category.

The `id` in the `purchases` table represents the purchase order (rows with a lower `id` are earlier
purchases).

Your code should output a table that includes every purchase the user has made. Additionally, the
table should include a boolean column with a value of `1` if the user has previously purchased a
product from its category and `0` if it’s their first time buying a product from that category.

_Note: Sort the results by the time purchased, in ascending order._

**Example:**

**Input:**

`purchases` table

Column | Type  
---|---  
`id` | INTEGER  
`product_name` | VARCHAR  
`product_category` | INTEGER  
  
**Output:**

Column | Type  
---|---  
`product_name` | VARCHAR  
`category_previously_purchased` | BOOLEAN  
  
Display results in the following way:

product_name | category_previously_purchased  
---|---  
toy car | 0  
toy plane | 1  
basketball | 0  
football | 1  
baseball | 1

In [1]:
# Question 35: Repeated Category Purchase
# 
# You’re analyzing a user’s purchases for a retail business.
#
# Each product belongs to a category. Your task is to identify which purchases represent
# the first
# time the user has bought a product from its own category and which purchases represent
# repeat
# purchases within the product category.
#
# The id in the purchases table represents the purchase order (rows with a lower id are
# earlier
# purchases).
#
# Your code should output a table that includes every purchase the user has made.
# Additionally, the
# table should include a boolean column with a value of 1 if the user has previously
# purchased a
# product from its category and 0 if it’s their first time buying a product from that
# category.
#
# _Note: Sort the results by the time purchased, in ascending order._

import pandas as pd
import numpy as np
from datetime import datetime

# Comprehensive mock data for the main problem and practice questions (12 rows)
purchases_data = {
    'id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    'user_id': [101, 102, 101, 103, 101, 102, 101, 104, 102, 103, 104, 101],
    'product_name': ['toy car', 'basketball', 'toy car', 'toy plane', 'toy plane', 'basketball', 'toy car', 'football', 'baseball', 'teddy bear', 'football', 'toy plane'],
    'product_category': [1, 2, 1, 1, 1, 2, 1, 3, 2, 4, 3, 1],
}
purchases = pd.DataFrame(purchases_data)

def solution():
    df = purchases.sort_values(by='id').reset_index(drop=True)
    df['category_previously_purchased'] = df.duplicated(subset=['product_category']).astype(int)
    return df[['product_name', 'category_previously_purchased']]

solution()

   product_name  category_previously_purchased
0       toy car                              0
1    basketball                              0
2       toy car                              1
3     toy plane                              1
4     toy plane                              1
5    basketball                              1
6       toy car                              1
7      football                              0
8      baseball                              1
9    teddy bear                              0
10     football                              1
11    toy plane                              1

### Practice Question 1: First Purchase per Category
**Problem:** Using the same `purchases` table, write a pandas query to return only the rows that represent the *first* time a product category was ever purchased. 

*Hint: Explore the `drop_duplicates` method.*

In [3]:
def practice_q1():
    # Write your solution here
    df = purchases.sort_values(by = 'id')
    df = df.drop_duplicates(subset = 'product_category',ignore_index=True)
    return df

practice_q1()

   id  user_id product_name  product_category
0   1      101      toy car                 1
1   2      102   basketball                 2
2   8      104     football                 3
3  10      103   teddy bear                 4

### Practice Question 2: User-Specific Repeat Purchases
**Problem:** The `purchases` table has a `user_id` column. Identify purchases where the *same user* bought the *same product* more than once. Create a boolean column `user_repeat_buy` that is `1` if the user bought that exact product before, and `0` otherwise.

*Hint: You can pass a list of multiple columns to the `subset` argument in `duplicated()`.*

In [48]:
def practice_q2():
    # Use the main 'purchases' DataFrame defined at the top
    df = purchases.sort_values(by='id').reset_index(drop=True)
    # Write your solution here
    df['repeat_prod_flag'] = df.duplicated(subset = ['user_id','product_name'],keep = 'last')
    return df

practice_q2()

    id  user_id product_name  product_category  repeat_prod_flag
0    1      101      toy car                 1              True
1    2      102   basketball                 2              True
2    3      101      toy car                 1              True
3    4      103    toy plane                 1             False
4    5      101    toy plane                 1              True
5    6      102   basketball                 2             False
6    7      101      toy car                 1             False
7    8      104     football                 3              True
8    9      102     baseball                 2             False
9   10      103   teddy bear                 4             False
10  11      104     football                 3             False
11  12      101    toy plane                 1             False

### Practice Question 3: Count Repeat Purchases per Category
**Problem:** Using the original `purchases` table, calculate the total number of repeat purchases (duplicates) for each `product_category`.

*Hint: Combine `duplicated()` with a `.groupby()` and a `.sum()` aggregate function.*

In [69]:
def practice_q3():
    # Write your solution here
    df = purchases.sort_values(by = ['product_name','id'])
    df['repeat_prod'] = df.duplicated(subset= 'product_name').astype(int)
    df = df.groupby('product_name').agg(repeat_buys = ('repeat_prod','sum')).reset_index().sort_values(by = 'repeat_buys',ascending = False)
    # df = df.groupby('product_name').agg(repeat_buys=('repeat_prod', 'sum'))
    return df

practice_q3()

  product_name  repeat_buys
4      toy car            2
5    toy plane            2
2     football            1
1   basketball            1
0     baseball            0
3   teddy bear            0